// File generated by FlutterFire CLI.
// ignoring_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3Apz7L2O90UQW11nehmTbJydkYAEaFM',
    appId: '1:330591683599:web:c5b6d214ae55782f05cf7a',
    messagingSenderId: '330591683599',
    projectId: 'zenno-aa3d5',
    authDomain: 'zenno-aa3d5.firebaseapp.com',
    storageBucket: 'zenno-aa3d5.firebasestorage.app',
    measurementId: 'G-HH9EPWR4N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tN9wyzILwbvb41yLOhfJr4mWOGDS-WE',
    appId: '1:330591683599:android:9cc750b60d5dd20d05cf7a',
    messagingSenderId: '330591683599',
    projectId: 'zenno-aa3d5',
    storageBucket: 'zenno-aa3d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Kq9sIJDmOos9Y1lipYewnDx8vex30nE',
    appId: '1:330591683599:ios:f26e4aba56362ae305cf7a',
    messagingSenderId: '330591683599',
    projectId: 'zenno-aa3d5',
    storageBucket: 'zenno-aa3d5.firebasestorage.app',
    iosBundleId: 'com.example.zenno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Kq9sIJDmOos9Y1lipYewnDx8vex30nE',
    appId: '1:330591683599:ios:f26e4aba56362ae305cf7a',
    messagingSenderId: '330591683599',
    projectId: 'zenno-aa3d5',
    storageBucket: 'zenno-aa3d5.firebasestorage.app',
    iosBundleId: 'com.example.zenno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ3Apz7L2O90UQW11nehmTbJydkYAEaFM',
    appId: '1:330591683599:web:0d47e8a681b9328405cf7a',
    messagingSenderId: '330591683599',
    projectId: 'zenno-aa3d5',
    authDomain: 'zenno-aa3d5.firebaseapp.com',
    storageBucket: 'zenno-aa3d5.firebasestorage.app',
    measurementId: 'G-9WTXEJ7660',
  );

}